# Site settings
title: حمید کرد
description: 'حافظ این حال عجب با که توان گفت که ما، بلبلانیم که در موسم گل خاموشیم'
url: 'http://hamid.id.ir'
baseurl: ''
timezone: Asia/Tehran
google_analytics: 'UA-51968105-2'
disqus_shortname: 'hamid-id-ir'
excerpt_separator: <!--more-->
cdn_address: '//cdn.takwp.ir/docs'
HTML_Lang: 'fa-IR'

author:
  name: 'Hamid Kurd'
  email_username: info
  email_domain: hamid.id.ir
  twitter_username: mer30hamid
#  facebook_username: hamidkurd
  github_username:  mer30hamid
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-gist']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'JekylMERun.cmd','minify.cmd','minify.js','node_modules','_site','jquery.min.js','jquery.timeago.min.js','main.js','animate.css','main.css','monokai.css','uno.css','CNAME']
